name: Build RAG Embeddings

on:
  workflow_dispatch:

jobs:
  build-embeddings:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyPDF2 python-docx

      - name: Run build script
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          HUGGINGFACE_EMBEDDING_MODEL: BAAI/bge-base-en-v1.5
        run: python scripts/rag/build_embeddings_hf.py

      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f server/rag/docstore.json server/rag/embeddings.json || true
          git commit -m "chore(rag): update embeddings (GH Action)" || echo "no changes to commit"
          git push origin HEAD:${GITHUB_REF##*/}
